services:
    saturnZ.ActiveUser.controller:
        class: saturnZ\ActiveUser\controller\ActiveUser
        arguments:
            - @config
            - @config_text
            - @request
            - @pagination
            - @dbal.conn
            - @auth
            - @template
            - @user
            - @controller.helper
            - %core.root_path%
            - %core.php_ext%
            - %core.table_prefix%
    saturnZ.ActiveUser.listener:
        class: saturnZ\ActiveUser\event\listener
        arguments:
            - @template
            - %core.root_path%
        tags:
            - { name: event.listener }
